#pragma once

const int NUMBER_OF_PLAYERS = 1;
const int PRIMARY_WEAPON_COST = 20;
const int PRIMARY_WEAPON_AMMO_SPEED = 400;
const int SECONDARY_WEAPON_COST = 1000;
const float SECONDARY_WEAPON_AMMO_RANGE = 100.0f;

const int ASTEROID_SPAWN_PER_MINUTE_BASE = 30;
const int ENEMY_SPAWN_PER_MINUTE_BASE = 1;
const int ASTEROID_SPAWN_PER_MINUTE_INCREASE = 10;
const int ENEMY_SPAWN_PER_MINUTE_INCREASE = 1;